config/routes.rb
RedmineApp::Application.routes.draw do
  resources :kanbans do 
    put 'sync', :on => :member
  end

  resources :kanbaniterations do 
    put 'sync', :on => :member
  end

  resources :admin_kanban_boards, :controller => 'admin_kanban_boards', :path => 'admin/kanban_boards', :except => [:show]
end

app/controllers/admin_kanban_boards_controller.rb
class AdminKanbanBoardsController < ApplicationController
  unloadable

  layout 'admin'

  before_filter :require_admin

  def index
    @resources = KanbanBoard.order
  end

  def new
    @resource = KanbanBoard.new
  end

  def create
    @resource = KanbanBoard.new(params[:resource])

    if @resource.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to admin_kanban_boards_path
    else
      render :action => :new
    end
  end

  def edit
    @resource = KanbanBoard.find(params[:id])

    if @resource.nil?
      redirect_to admin_kanban_boards_path
    end
  end

  def update
    @resource = KanbanBoard.find(params[:id])
    @resource.update_attributes(params[:resource])

    if @resource.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to admin_kanban_boards_path
    else
      render :action => :edit
    end
  end

  def destroy
    @resource = KanbanBoard.find(params[:id])
    if @resource && @resource.destroy
      flash[:notice] = l(:notice_successful_delete)
    end
    redirect_to admin_kanban_boards_path
  end
end

app/helpers/admin_kanban_boards_helper.rb
module AdminKanbanBoardsHelper
  def staff_role_select(f, board)
    rv = f.label(:staff_role)

    selected = (board && board.settings && board.settings[:staff_role]) ? board.settings[:staff_role].to_i : 0
    rv += select_tag('resource[staff_role]',
          content_tag(:option, '') + options_from_collection_for_select(Role.all, :id, :name, selected),
          { :required => false }
    )

    rv
  end

  def pane_issue_status_select_for_open_issues(f, board, pane_name, html_opts = {})
    var_name = "pane_#{pane_name}_issue_status".to_sym

    rv = f.label(var_name)

    selected = board && board.settings && board.settings[var_name] ? board.settings[var_name].to_i : 0
    rv += select_tag("resource[#{var_name}]",
      content_tag(:option, '') + options_from_collection_for_select(IssueStatus.all, :id, :name, selected), html_opts)

    rv
  end

  def pane_issue_status_select_for_closed_issues(f, board, pane_name)
    var_name = "pane_#{pane_name}_issue_status".to_sym

    rv = f.label(var_name)

    selected = board && board.settings && board.settings[var_name] ? board.settings[var_name].to_i : 0
    rv += select_tag("resource[#{var_name}]",
      content_tag(:option, '') +
      options_from_collection_for_select(IssueStatus.all(:conditions => {:is_closed => true}), :id, :name, selected),
      { :required => true }
    )

    rv
  end
end

app/views/admin_kanban_boards/_form.html.erb
<%= error_messages_for 'resource' %>

<div class="box tabular">
  <p><%= f.text_field :name, :required => true, :size => 60 %></p>
</div>

<div class="box tabular">
  <fieldset id="resource_general_settings">
    <legend><%= l(:kanban_text_general_settings) %></legend>
    <p>
      <%= staff_role_select(f, @resource) %>
    </p>
  </fieldset>
  <fieldset id="resource_pane_values">
    <legend><%= l(:kanban_text_pane_settings) %></legend>
    <%= content_tag(:p, l(:kanban_text_pane_settings_description)) %>
    <p>
      <%= pane_issue_status_select_for_open_issues(f, @resource, :incoming) %>
      <%= f.text_field :pane_incoming_size, :no_label => true %>
      <span><%= l(:pane_incoming_size_um) %></span>
    </p>
    <p>
      <%= pane_issue_status_select_for_open_issues(f, @resource, :backlog) %>
      <%= f.text_field :pane_backlog_size, :no_label => true %>
      <span><%= l(:pane_backlog_size_um) %></span>
    </p>
    <p>
      <%= pane_issue_status_select_for_open_issues(f, @resource, :quick, :required => false) %>
      <%= f.text_field :pane_quick_size, :no_label => true %>
      <span><%= l(:pane_quick_size_um) %></span>
    </p>
    <p>
      <%= pane_issue_status_select_for_open_issues(f, @resource, :selected, :required => false) %>
      <%= f.text_field :pane_selected_size, :no_label => true %>
      <span><%= l(:pane_selected_size_um) %></span>
    </p>
    <p>
      <%= pane_issue_status_select_for_open_issues(f, @resource, :active) %>
      <%= f.text_field :pane_active_size, :no_label => true %>
      <span><%= l(:pane_active_size_um) %></span>
    </p>
    <p>
      <%= pane_issue_status_select_for_open_issues(f, @resource, :testing) %>
      <%= f.text_field :pane_testing_size, :no_label => true %>
      <span><%= l(:pane_testing_size_um) %></span>
    </p>
    <p>
      <%= pane_issue_status_select_for_open_issues(f, @resource, :finished) %>
      <%= f.text_field :pane_finished_size, :no_label => true %>
      <span><%= l(:pane_finished_size_um) %></span>
    </p>
    <p>
      <%= pane_issue_status_select_for_open_issues(f, @resource, :canceled) %>
      <%= f.text_field :pane_canceled_size, :no_label => true %>
      <span><%= l(:pane_canceled_size_um) %></span>
    </p>
  </fieldset>
</div>

<%= javascript_tag "$('#resource_name').focus();" %>

app/views/admin_kanban_boards/edit.html.erb
<h2><%= link_to l(:label_kanban_board_plural), admin_kanban_boards_path %> &#187; <%=h @resource.to_label %></h2>

<%= labelled_form_for :resource, @resource, { :url => admin_kanban_board_url, :html => { :method => :put } } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= submit_tag l(:button_submit) %>
<% end %>

app/views/admin_kanban_boards/index.html.erb
<div class="contextual">
  <%= link_to l(:label_kanban_board_new), new_admin_kanban_board_path, :class => 'icon icon-add' %>
</div>

<h2><%=l(:label_kanban_board_plural)%></h2>

<div class="autoscroll">
<table class="list">
  <thead><tr>
  <th><%=l(:field_name)%></th>
  <th>&nbsp;</th>
  </tr></thead>
  <tbody>
<% @resources.each do |resource| %>
  <tr class="<%= cycle("odd", "even") %>">
    <td class="name"><span><%= link_to resource.name, edit_admin_kanban_board_path(resource) %></span></td>
    <td class="buttons">
      <%= link_to(l(:button_delete), admin_kanban_board_path(resource), :method => :delete, :confirm => l(:text_kanban_board_destroy_confirmation), :class => 'icon icon-del') %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>
</div>

<% html_title(l(:label_kanban_board_plural)) -%>

app/views/admin_kanban_boards/new.html.erb
<h2><%= link_to l(:label_kanban_board_plural), admin_kanban_boards_path %> &#187; <%=l(:label_kanban_board_new)%></h2>

<%= labelled_form_for :resource, @resource, { :url => admin_kanban_boards_url } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= submit_tag l(:button_create) %>
<% end %>