config/routes.rb
RedmineApp::Application.routes.draw do
  resources :kanbans do 
    put 'sync', :on => :member
  end

  resources :kanbaniterations do 
    put 'sync', :on => :member
  end

  resources :admin_kanban_boards, :controller => 'admin_kanban_boards', :path => 'admin/kanban_boards', :except => [:show]
end

app/models/kanban.rb
class Kanban
  attr_accessor :incoming_pane, :backlog_pane, :quick_pane, :canceled_pane, :finished_pane, :active_pane, :testing_pane, :selected_pane
  
  attr_accessor :board
  attr_accessor :incoming_issues
  attr_accessor :quick_issues
  attr_accessor :backlog_issues
  attr_accessor :selected_issues
  attr_accessor :active_issues
  attr_accessor :testing_issues
  attr_accessor :finished_issues
  attr_accessor :canceled_issues
  attr_accessor :settings
  attr_accessor :users

  def initialize(board)
    self.board = board

    @incoming_pane = KanbanPane::IncomingPane.new(self)
    @backlog_pane = KanbanPane::BacklogPane.new(self)
    @quick_pane = KanbanPane::QuickPane.new(self)
    @canceled_pane = KanbanPane::CanceledPane.new(self)
    @finished_pane = KanbanPane::FinishedPane.new(self)
    @active_pane = KanbanPane::ActivePane.new(self)
    @testing_pane = KanbanPane::TestingPane.new(self)
    @selected_pane = KanbanPane::SelectedPane.new(self)
    
    @settings = settings_by_pane
    @users = get_users
  end

  def self.non_kanban_issues_panes
     ["incoming","backlog", "quick","finished","canceled"]
  end

  def self.kanban_issues_panes
    ['selected','active','testing']
  end

  def self.valid_panes
    kanban_issues_panes + non_kanban_issues_panes
  end

  def self.staffed_panes
    ['active','testing','finished','canceled']
  end

  def settings_by_pane
    if @settings_by_pane.nil?
      @settings_by_pane = {
        'panes' => {
          'incoming' => {
            'status' => self.board.pane_incoming_issue_status,
            'limit' => self.board.pane_incoming_size
          },
          'backlog' => {
            'status' => self.board.pane_backlog_issue_status,
            'limit' => self.board.pane_backlog_size
          },
          'quick' => {
            'status' => self.board.pane_quick_issue_status,
            'limit' => self.board.pane_quick_size
          },
          'selected' => {
            'status' => self.board.pane_selected_issue_status,
            'limit' => self.board.pane_selected_size
          },
          'active' => {
            'status' => self.board.pane_active_issue_status,
            'limit' => self.board.pane_active_size
          },
          'testing' => {
            'status' => self.board.pane_testing_issue_status,
            'limit' => self.board.pane_testing_size
          },
          'finished' => {
            'status' => self.board.pane_finished_issue_status,
            'limit' => self.board.pane_finished_size
          },
          'canceled' => {
            'status' => self.board.pane_canceled_issue_status,
            'limit' => self.board.pane_canceled_size
          }
        },
        'staff_role' => self.board.staff_role.to_i
      }
    end

    @settings_by_pane
  end

  def incoming_issues
    @incoming_issues ||= incoming_pane.get_issues
  end

  def quick_issues
    @quick_issues ||= quick_pane.get_issues
  end

  def backlog_issues
    quick_issues # Needs to load quick_issues
    @backlog_issues ||= backlog_pane.get_issues(:exclude_ids => quick_issue_ids)
  end

  def selected_issues
    @selected_issues ||= selected_pane.get_issues
  end

  def active_issues
    @active_issues ||= active_pane.get_issues(:users => get_users)
  end

  def testing_issues
    @testing_issues ||= testing_pane.get_issues(:users => get_users)
  end

  def finished_issues
    @finished_issues ||= finished_pane.get_issues
  end

  def canceled_issues
    @canceled_issues ||= canceled_pane.get_issues
  end

  def get_users
    role = Role.find_by_id(@settings["staff_role"].to_i)
    @users = role.members.collect(&:user).uniq.compact.sort if role
    @users ||= []
    @users = move_current_user_to_front
    #@users << UnknownUser.instance
    @users
  end
  
  def quick_issue_ids
    if quick_issues.present?
      quick_issues.collect {|ary| ary[1] }.flatten.collect(&:id)
    else
      []
    end
  end

  # Updates +target_pane+ so that the KanbanIssues match +sorted_issues+
  def update_sorted_issues(target_pane, sorted_issues, user_id=nil)
    if Kanban.kanban_issues_panes.include?(target_pane)
      if sorted_issues.blank? && !target_pane.blank?
        self.board.kanban_issues.destroy_all(:state => target_pane, :user_id => user_id)
      else
        # Remove items that are in the database but not in the sorted_issues
        if user_id
          self.board.kanban_issues.where(['state = ? AND user_id = ? AND issue_id NOT IN (?)', target_pane, user_id, sorted_issues]).map(&:destroy)
        else
          self.board.kanban_issues.where(['state = ? AND issue_id NOT IN (?)', target_pane, sorted_issues]).map(&:destroy)
        end
          
        sorted_issues.each_with_index do |issue_id, zero_position|
          kanban_issue = self.board.kanban_issues.find_by_issue_id(issue_id)
          if kanban_issue
            if kanban_issue.state != target_pane
              # Change state
              kanban_issue.send(target_pane.to_sym)
            end
            kanban_issue.user_id = user_id unless target_pane == 'selected'
            kanban_issue.position = zero_position + 1 # acts_as_list is 1 based
            kanban_issue.save
          else
            kanban_issue = self.board.kanban_issues.new
            kanban_issue.issue_id = issue_id
            kanban_issue.state = target_pane
            kanban_issue.user_id = user_id unless target_pane == 'selected'
            kanban_issue.position = (zero_position + 1)
            kanban_issue.save
            # Need to resave since acts_as_list automatically moves a
            # new issue to the bottom on create
            kanban_issue.insert_at(zero_position + 1)
          end
        end
      end
    end
  end

  # Updates the Issue with +issue_id+ to change it's
  # - status to the IssueStatus set for the +to+ pane
  # - assignment to the +target_user+ on staffed panes
  def update_issue_attributes(issue_id, from, to, updating_user, target_user=nil)
    issue = Issue.find_by_id(issue_id)

    pane_settings = @settings['panes'][to]
    if pane_settings && pane_settings['status']
      new_status = IssueStatus.find_by_id(pane_settings['status'].to_i)
    end
      
    if issue && new_status
      issue.init_journal(updating_user)
      issue.status = new_status

      if Kanban.staffed_panes.include?(to) && !target_user.nil? && target_user.is_a?(User)
        issue.assigned_to = target_user
      end

      issue.save
    else
      false
    end
  end

  private

  def move_current_user_to_front
    if user = @users.delete(User.current)
      @users.unshift(user)
    else
      @users
    end
  end
end

app/controllers/kanbans_controller.rb
class KanbansController < ApplicationController
  unloadable
  helper :kanbans
  include KanbansHelper

  before_filter :authorize
  before_filter :setup_board, :only => [:show, :update]

  def index
    @resources = KanbanBoard.order
  end

  def show
    render 'kanbans/show'
  end

  def update
    load_user_and_user_id

    src_pane = params[:from]
    dst_pane = params[:to]
    src_issue = params[:issue_id]
    issues_requested_on_dst_pane = params[:to_issue]
    updating_user = User.current

    # src_pane = "incoming"
    # dst_pane = "finished"
    # src_issue = 3
    # issues_requested_on_dst_pane = ["3", "4"]
    # @to_user_id = 9
    # @to_user = #<User id: 9, login: "developmentteam1" ...
    # @from_user = nil

    saved = @kanban.update_issue_attributes(issues_requested_on_dst_pane, src_pane, dst_pane, updating_user, @to_user)

    if Kanban.kanban_issues_panes.include?(dst_pane)
      @kanban.update_sorted_issues(dst_pane, issues_requested_on_dst_pane, @to_user_id)
    end
	
    respond_to do |format|
      if saved 
        format.html {
	        flash[:notice] = l(:kanban_text_saved)
          redirect_to kanban_path
        }
        format.js {
          render :text => ActiveSupport::JSON.encode({
             'from' => render_pane_to_js(src_pane, @from_user),
             'to' => render_pane_to_js(dst_pane, @to_user),
             'additional_pane' => render_pane_to_js(params[:additional_pane])
           })
        	}
      else
        format.html {
          flash[:error] = l(:kanban_text_error_saving)
          redirect_to kanban_path
        }
        format.js { 
          render({:text => ({}.to_json), :status => :bad_request})
        }
      end
    end
  end

  def sync
    Issue.sync_with_kanban
    
    respond_to do |format|
      format.html {
        flash[:notice] = l(:kanban_text_notice_sync)
        redirect_to kanban_path
      }
    end
  end

  protected
  # Override the default authorize and add in the global option. This will allow
  # the user in if they have any roles with the correct permission
  def authorize(ctrl = params[:controller], action = params[:action])
    allowed = User.current.allowed_to?({:controller => ctrl, :action => action}, nil, { :global => true})
    allowed ? true : deny_access
  end

  helper_method :allowed_to_edit?
  def allowed_to_edit?
    User.current.allowed_to?({:controller => params[:controller], :action => 'update'}, nil, :global => true)
  end

  helper_method :allowed_to_manage?
  def allowed_to_manage?
    User.current.allowed_to?(:manage_kanban, nil, :global => true)
  end

  # Sets instance variables based on the parameters
  # * @from_user_id
  # * @from_user
  # * @to_user_id
  # * @to_user
  def load_user_and_user_id
    @from_user_id, @from_user = *extract_user_id_and_user(params[:from_user_id])
    @to_user_id, @to_user = *extract_user_id_and_user(params[:to_user_id])
  end

  def extract_user_id_and_user(user_id_param)
    user_id = nil
    user = nil

    case user_id_param
    when 'null' # Javascript nulls
      user_id = nil
      user = nil
    when '0' # Unknown user
      user_id = 0
      user = UnknownUser.instance
    else
      user_id = user_id_param
      user = User.find_by_id(user_id) # only needed for user specific views
    end

    return [user_id, user]
  end

  def setup_board
    @board = KanbanBoard.find(params[:id])

    if @board.nil?
      redirect_to kanbans_path
    end

    @kanban = Kanban.new(@board)
    @settings = @board.settings
  end
end

app/helpers/kanbans_helper.rb
module KanbansHelper
  def name_to_css(name)
    name.gsub(' ','-').downcase
  end

  def render_pane_to_js(pane, user=nil)
    if Kanban.valid_panes.include?(pane)
	    return render_to_string(:partial => pane, :locals => {:user => user })
    else
      ''
    end
  end

  # Returns the CSS class for jQuery to hook into.  Current users are
  # allowed to Drag and Drop items into their own list, but not other
  # people's lists
  def allowed_to_assign_staffed_issue_to(user)
    if allowed_to_manage? || User.current == user
      'allowed'
    else
      ''
    end
  end

  def over_pane_limit?(limit, counter)
    if !counter.nil? && !limit.nil? && counter.to_i >= limit.to_i # 0 based counter
      return 'over-limit'
    else
      return ''
    end
  end

  # Was the last journal with a note created by someone other than the
  # assigned to user?
  def updated_note_on_issue?(issue)
    if issue && issue.journals.present?
      last_journal_with_note = issue.journals.select {|journal| journal.notes.present?}.last
      last_journal_with_note && issue.assigned_to_id != last_journal_with_note.user_id
    end
  end

  def kanban_issue_css_classes(issue)
    css = 'kanban-issue ' + issue.css_classes
    if User.current.logged? && !issue.assigned_to_id.nil? && issue.assigned_to_id != User.current.id
      css << ' assigned-to-other'
    end
    css << ' issue-behind-schedule' if issue.behind_schedule?
    css << ' issue-overdue' if issue.overdue?
    css
  end

  def issue_icon_link(issue)
    if Setting.gravatar_enabled? && issue.assigned_to
      img = avatar(issue.assigned_to, {
        :class => 'gravatar icon-gravatar',
        :size => 10,
        :title => l(:field_assigned_to) + ": " + issue.assigned_to.name
      })
      link_to(img, :controller => 'issues', :action => 'show', :id => issue)
    else
      link_to(image_tag('ticket.png', :style => 'float:left;'), :controller => 'issues', :action => 'show', :id => issue)
    end
  end

  def column_configured?(kanban, column)
    case column
    when :unstaffed
      kanban.incoming_pane.configured? || kanban.backlog_pane.configured?
    when :selected
      kanban.quick_pane.configured? || kanban.selected_pane.configured?
    when :staffed
      true # always
    end
  end

  # Calculates the width of the column.  Max of 96 since they need
  # some extra for the borders.
  def column_width(kanban, column)
    # weights of the columns
    column_ratios = {
      :unstaffed => 1,
      :selected => 1,
      :staffed => 6
    }
    return 0.0 if column == :unstaffed && !column_configured?(kanban, :unstaffed)
    return 0.0 if column == :selected && !column_configured?(kanban, :selected)
    
    visible = 0
    visible += column_ratios[:unstaffed] if column_configured?(kanban, :unstaffed)
    visible += column_ratios[:selected] if column_configured?(kanban, :selected)
    visible += column_ratios[:staffed] if column_configured?(kanban, :staffed)
    
    return ((column_ratios[column].to_f / visible) * 96).round(2)
  end

  # Calculates the width of the column.  Max of 96 since they need
  # some extra for the borders.
  def staffed_column_width(kanban, column)
    # weights of the columns
    column_ratios = {
      :user => 1,
      :active => 1.25,
      :testing => 2,
      :finished => 2,
      :canceled => 2
    }
    return 0.0 if column == :active && !kanban.active_pane.configured?
    return 0.0 if column == :testing && !kanban.testing_pane.configured?
    return 0.0 if column == :finished && !kanban.finished_pane.configured?
    return 0.0 if column == :canceled && !kanban.canceled_pane.configured?

    visible = 0
    visible += column_ratios[:user]
    visible += column_ratios[:active] if kanban.active_pane.configured?
    visible += column_ratios[:testing] if kanban.testing_pane.configured?
    visible += column_ratios[:finished] if kanban.finished_pane.configured?
    visible += column_ratios[:canceled] if kanban.canceled_pane.configured?
    
    return ((column_ratios[column].to_f / visible) * 96).round(2)
  end

  def render_priority_for_issue(issue)
    return "" unless issue.priority
    raw("<br/><span style='color:blue'> Priority: #{h(issue.priority.name)}</span>\n")
  end

  def render_custom_field_developer_for_kanban(issue)
    return if issue.custom_field_values.empty?
    s = ""
    #value = issue.custom_field_values.select{|item| item.custom_field.name == 'Developer'}.last	
    value = issue.custom_value_for(40)
    return "" unless value
    return "" unless value.value
    if !value.value.blank?
    	s << "<br/><span style='color:green;font-weight:bolder'> #{ h(value.custom_field.name) }: #{ simple_format_without_paragraph(h(show_value(value))) }</span>\n"
    end
   raw(s)
  end
	    
  # Return a string used to display a custom value
  def show_value(custom_value)
    return "" unless custom_value
    format_value(custom_value.value, custom_value.custom_field.field_format)
  end

  # Return a string used to display a custom value
  def format_value(value, field_format)
    Redmine::CustomFieldFormat.format_value(value, field_format) # Proxy
  end
  
  def issue_url(issue)
    url_for(:controller => 'issues', :action => 'show', :id => issue)
  end
end

app/views/kanbans/_active.html.erb
<ol id="active-issues-user-<%= h user.id -%>" class="active-issues <%= allowed_to_assign_staffed_issue_to(user) -%>">
  <% if @kanban.active_issues[user].empty? %>
    <%= render :partial => 'empty_issue' %>
  <% else %>
  <%= render(:partial => 'issue',
    :collection => @kanban.active_issues[user].collect(&:issue),
    :locals => { :limit => Setting['plugin_redmine_kanban']["panes"]["active"]["limit"].to_i }) %>
  <% end %>
</ol>

app/views/kanbans/_backlog.html.erb
<%= content_tag(:h3, l(:kanban_text_backlog)) %>
<ol id="backlog-issues">
  <% if @kanban.backlog_issues.empty? %>
    <%= render :partial => 'empty_issue' %>
  <% else %>
    <%= render :partial => 'grouped_issues', :object => @kanban.backlog_issues %>
  <% end %>
</ol>

app/views/kanbans/_canceled.html.erb
<ol id="canceled-issues-user-<%= h user.id -%>" class="canceled-issues <%= allowed_to_assign_staffed_issue_to(user) -%>">
  <% if @kanban.canceled_issues.blank? ||  @kanban.canceled_issues[user].blank? %>
    <%= render :partial => 'empty_issue' %>
  <% else %>
    <%= render(:partial => 'issue', :collection => @kanban.canceled_issues[user]) %>
  <% end %>
</ol>

app/views/kanbans/_empty_issue.html.erb
<li class="kanban-issue">
  <%= l(:kanban_text_nothing) %>
</li>

app/views/kanbans/_finished.html.erb
<ol id="finished-issues-user-<%= h user.id -%>" class="finished-issues <%= allowed_to_assign_staffed_issue_to(user) -%>">
  <% if @kanban.finished_issues.blank? ||  @kanban.finished_issues[user].blank? %>
    <%= render :partial => 'empty_issue' %>
  <% else %>
    <%= render(:partial => 'issue', :collection => @kanban.finished_issues[user]) %>
  <% end %>
</ol>

app/views/kanbans/_grouped_issues.html.erb
<% grouped_issues.each do |priority, issues| %>
  <%= content_tag(:p, h(priority.name)) %>
  <ol class="<%= name_to_css(priority.name) %>">
    <%= render :partial => 'issue', :collection => issues %>
  </ol>
<% end %>

app/views/kanbans/_incoming.html.erb
<%= content_tag(:h3, l(:kanban_text_incoming)) %>
<ol id="incoming-issues">
  <%= render :partial => 'issue', :collection => @kanban.incoming_issues %>
</ol>

app/views/kanbans/_issue.html.erb
<% if issue %>
<li id="issue_<%= issue.id %>" class="<%= over_pane_limit?(limit, issue_counter) if defined?(limit) -%> <%= kanban_issue_css_classes(issue) %>">
  <div class="issue-details">

    <div class="issue-details-header">
      <div class="icons">
        <%= issue_icon_link(issue) %>
        <%= call_hook(:view_kanbans_issue_details, :issue => issue) %>
        <%= image_tag('comment.png', :class => 'updated-note', :alt => l(:kanban_text_updated_issue), :title => l(:kanban_text_updated_issue)) if updated_note_on_issue?(issue) %>
      </div>
      <a href="<%= issue_url(issue) %>">#<%= h(issue.id) %></a> - <%= h(issue.fixed_version) if issue.project %> <%= render_custom_field_developer_for_kanban(issue) %>
    </div>
    
    <div class="issue-details-body"><%= h(issue.subject) %></div>
  </div>
</li>
<% end %>

app/views/kanbans/_quick.html.erb
<%= content_tag(:h3, l(:kanban_text_quick_tasks)) %>
<ol id="quick-issues">
  <% if @kanban.quick_issues.empty? %>
    <%= render :partial => 'empty_issue' %>
  <% else %>
    <%= render :partial => 'grouped_issues', :object => @kanban.quick_issues %>
  <% end %>
</ol>

app/views/kanbans/_selected.html.erb
<%= content_tag(:h3, l(:kanban_text_selected_requests)) %>
<ol id="selected-issues" class="<%= allowed_to_assign_staffed_issue_to(nil) -%>">
  <% if @kanban.selected_issues.empty? %>
    <%= render :partial => 'empty_issue' %>
  <% else %>
    <%= render(:partial => 'issue',
      :collection => @kanban.selected_issues.collect(&:issue),
      :locals => { :limit => Setting['plugin_redmine_kanban']["panes"]["selected"]["limit"].to_i }) %>
  <% end %>
</ol>

app/views/kanbans/_testing.html.erb
<ol id="testing-issues-user-<%= h user.id -%>" class="testing-issues <%= allowed_to_assign_staffed_issue_to(user) -%>">
  <% if @kanban.testing_issues[user].empty? %>
    <%= render :partial => 'empty_issue' %>
  <% else %>
    <%= render(:partial => 'issue',
      :collection => @kanban.testing_issues[user].collect(&:issue),
      :locals => { :limit => Setting['plugin_redmine_kanban']["panes"]["testing"]["limit"].to_i }) %>
  <% end %>
</ol>

app/views/kanbans/_user.html.erb
<div class="staff">
  <div id="staffed-requests-header" class="staff">
    <%= content_tag(:div, content_tag(:h3, l(:kanban_text_user)), :class => "staffed-column user", :style => "width: #{staffed_column_width(@kanban, :user)}%") %>
    <%= content_tag(:div, content_tag(:h3, l(:kanban_text_active)), :class => "staffed-column active", :style => "width: #{staffed_column_width(@kanban, :active)}%") if @kanban.active_pane.configured? %>
    <%= content_tag(:div, content_tag(:h3, l(:kanban_text_testing)), :class => "staffed-column testing", :style => "width: #{staffed_column_width(@kanban, :testing)}%") if @kanban.testing_pane.configured? %>
    <%= content_tag(:div, content_tag(:h3, l(:kanban_text_finished_requests)), :class => "staffed-column finished", :style => "width: #{staffed_column_width(@kanban, :finished)}%") if @kanban.finished_pane.configured? %>
    <%= content_tag(:div, content_tag(:h3, l(:kanban_text_canceled_requests)), :class => "staffed-column canceled", :style => "width: #{staffed_column_width(@kanban, :canceled)}%") if @kanban.canceled_pane.configured? %>
  </div>
  <div style="clear:both"></div>

  <div id="user-<%= h user.id -%>" class="staffed-column pane user" style="width: <%= staffed_column_width(@kanban, :user) %>%">
    <%= link_to_user(user) %>
    <%= call_hook(:view_kanbans_user_name, :user => user) %>
  </div>
  <% if @kanban.active_pane.configured? %>
    <div id="active-<%= h user.id -%>" class="staffed-column pane active user-<%= h user.id -%>" style="width: <%= staffed_column_width(@kanban, :active) %>%">
      <%= render(:partial => 'active', :locals => {:user => user}) %>
    </div>
  <% end %>
  <% if @kanban.testing_pane.configured? %>
    <div id="testing-<%= h user.id -%>" class="staffed-column pane testing user-<%= h user.id -%>" style="width: <%= staffed_column_width(@kanban, :testing) %>%">
      <%= render(:partial => 'testing', :locals => {:user => user}) %>
    </div>
  <% end %>
  <% if @kanban.finished_pane.configured? %>
    <div id="finished-<%= h user.id -%>" class="staffed-column pane finished user-<%= h user.id -%>" style="width: <%= staffed_column_width(@kanban, :finished) %>%">
      <%= render(:partial => 'finished', :locals => {:user => user}) %>
    </div>
  <% end %>
  <% if @kanban.canceled_pane.configured? %>
    <div id="canceled-<%= h user.id -%>" class="staffed-column pane canceled user-<%= h user.id -%>" style="width: <%= staffed_column_width(@kanban, :canceled) %>%">
      <%= render(:partial => 'canceled', :locals => {:user => user}) %>
    </div>
  <% end %>
  <div style="clear:both"></div>
</div>

app/views/kanbans/index.html.erb
<div class="contextual">
  <%= l(:label_kanban_board_plural) %>
</div>

<h2><%=l(:label_kanban_board_plural)%></h2>

<div class="autoscroll">
  <ol>
  <% @resources.each do |resource| %>
    <li>
      <%= link_to resource.to_label, kanban_path(resource) %>
      (<%= link_to l(:kanban_iteration_link_label), kanbaniteration_path(resource) %>)
    </li>
  <% end %>
  </ol>
</div>

<% html_title(l(:label_kanban_board_plural)) -%>

app/views/kanbans/show.html.erb
<% html_title l(:kanban_title) %>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'redmine_kanban.css', :plugin => "redmine_kanban" %>
  <%= javascript_include_tag 'jquery-1.3.2.min.js', :plugin => 'redmine_kanban' %>
  <%= javascript_include_tag 'jquery-ui-1.7.2.custom.min.js', :plugin => 'redmine_kanban' %>
  <%= javascript_include_tag 'jquery.json-1.3.min.js', :plugin => 'redmine_kanban' %>
  <%= javascript_include_tag 'jquery.ajax_queue.js', :plugin => 'redmine_kanban' %>
  <%= javascript_tag("jQuery.noConflict();") %>
  <% if allowed_to_edit? %>
    <%= javascript_include_tag 'kanban.js', :plugin => 'redmine_kanban' %>
    <script type="application/javascript">jQuery('document').ready(function () { RedmineKanban.Board(<%=@board.id%>); } )</script>
  <% end %>
<% end %>

<div class="flash error" style="display:none"></div>

<h2><%=h @board.to_label %></h2>

<script>
  setTimeout( "window.location.reload(false)", 120*1000 );
</script>

<div class="contextual">
  <% if User.current.allowed_to?(:edit_kanban, nil, :global => true) %>
    <%= link_to(l(:kanban_text_sync), sync_kanban_url, :method => :put, :class => 'icon icon-reload') %>
  <% end %>
  <%= link_to_function(l(:kanban_text_color_help), "$('#color-help').slideToggle();", :class => 'icon icon-info') %>
</div>

<p class="general-help"><%= l(:kanban_text_general_help) %></p>

<div id="color-help" style="display:none;">
  <%= content_tag(:h3, l(:kanban_text_color_help)) %>
  <ul>
    <li class="normal-color"><%=raw l(:kanban_text_normal_color) %></li>
    <li class="assigned-to-me-color"><%=raw l(:kanban_text_assigned_to_me_color) %></li>
    <li class="behind-schedule-color"><%=raw l(:kanban_text_behind_schedule_color) %></li>
    <li class="overdue-color"><%=raw l(:kanban_text_overdue_color) %></li>
    <li class="over-wip-color"><%=raw l(:kanban_text_over_wip_color) %></li>
  </ul>
</div>

<div id="kanban">
  <% if @kanban.incoming_pane.configured? || @kanban.backlog_pane.configured? %>
    <div id="unstaffed-requests" class="column" style="width: <%= column_width(@kanban, :unstaffed) %>%">

      <% if @kanban.incoming_pane.configured? %>
        <div id="incoming" class="pane">
          <%= render :partial => 'incoming' %>
        </div>
      <% end %>

      <% if @kanban.backlog_pane.configured? %>
        <div id="backlog" class="pane">
          <%= render :partial => 'backlog' %>
        </div>
      <% end %>

    </div>
  <% end %>

  <% if @kanban.quick_pane.configured? || @kanban.selected_pane.configured? %>
    <div id="selected-requests" class="column" style="width: <%= column_width(@kanban, :selected) %>%">
      <% if @kanban.quick_pane.configured? %>
        <div id="quick-tasks" class="pane">
          <%= render :partial => 'quick' %>
        </div>
      <% end %>

      <% if @kanban.selected_pane.configured? %>
        <div id="selected-tasks"class="pane">
          <%= render :partial => 'selected' %>
        </div>
      <% end %>

    </div>
  <% end %>

  <div id="staffed-requests" class="column" style="width: <%= column_width(@kanban, :staffed) %>%">
    <%= render :partial => 'user', :collection => @kanban.users %>
  </div>
</div>